version: '3.8'

services:

  redis:
    image: redis:7.2-alpine
    container_name: fx-redis
    ports:
      - "16379:6379"
    command: redis-server --requirepass fx_steam12!@ --appendonly yes

  kafka:
    image: apache/kafka:4.0.2
    container_name: fx-kafka
    ports:
      - "9092:9092"

  zipkin:
    image: openzipkin/zipkin
    container_name: fx-zipkin
    ports:
      - "9411:9411"