INSERT INTO currency_pair
    (symbol, country_name)
VALUES ('USD-KRW', '미국'),
       ('EUR-KRW', '유럽'),
       ('JPY-KRW', '일본'),
       ('GBP-KRW', '영국'),
       ('CNY-KRW', '중국'),
       ('HKD-KRW', '홍콩'),
       ('AUD-KRW', '호주'),
       ('CAD-KRW', '캐나다'),
       ('NZD-KRW', '뉴질랜드'),
       ('CHF-KRW', '스위스'),
       ('SGD-KRW', '싱가포르'),
       ('THB-KRW', '태국'),
       ('TWD-KRW', '대만'),
       ('VND-KRW', '베트남'),
       ('INR-KRW', '인도'),
       ('IDR-KRW', '인도네시아'),
       ('MYR-KRW', '말레이시아'),
       ('PHP-KRW', '필리핀'),
       ('RUB-KRW', '러시아'),
       ('AED-KRW', '아랍에미리트');