server:
  port: 8080

spring:
  application:
    name: fx-gateway
  profiles:
    active: local

  reactor:
    context-propagation: auto

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: fx-stream-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/rates/**
              filters:
                - StripPrefix=2

            - id: fx-notification-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/notification/**
              filters:
                - StripPrefix=2

            - id: fx-auth-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: health,info

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

jwt:
  secret: this-is-my-super-secret-key-with-more-than-32-characters-12345678