server:
  port: 8081

spring:
  application:
    name: fx-stream-service

  data:
    redis:
      host: localhost
      port: 16379
      password: fx_steam12!@
      database: 0

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%20.20thread] [%X{traceId}] [%-5level] %logger{36} - %msg%n"